from __future__ import annotations
from enum import IntEnum


class Key(IntEnum):
    # Slot values generated by calibrate.py on 2026-04-21 11:00:09
    # Each entry was verified by lighting the slot and recording the
    # physical key the user pressed in response.
    A            = 0
    B            = 1
    C            = 2
    D            = 3
    E            = 4
    F            = 5
    G            = 6
    H            = 7
    I            = 8
    J            = 9
    K            = 10
    L            = 11
    M            = 12
    N            = 13
    O            = 14
    P            = 15
    Q            = 16
    R            = 17
    S            = 18
    T            = 19
    U            = 20
    V            = 21
    W            = 22
    X            = 23
    Z            = 24
    Y            = 25
    N1           = 26
    N2           = 27
    N3           = 28
    N4           = 29
    N5           = 30
    N6           = 31
    N7           = 32
    N8           = 33
    N9           = 34
    N0           = 35
    ENTER        = 36
    ESC          = 37
    BACKSPACE    = 38
    TAB          = 39
    SPACE        = 40
    QUOTE        = 41
    GRAVE        = 42
    LBRACKET     = 43
    # slot  44 = '¨' (skipped / unmapped)
    # slot  45 = '<skip>' (skipped / unmapped)
    BACKSLASH    = 46
    SEMICOLON    = 47
    # slot  48 = 'ä' -> duplicate of QUOTE at slot 41, skipped
    # slot  49 = '§' (skipped / unmapped)
    COMMA        = 50
    PERIOD       = 51
    MINUS        = 52
    CAPS_LOCK    = 53
    F1           = 54
    F2           = 55
    F3           = 56
    F4           = 57
    F5           = 58
    F6           = 59
    F7           = 60
    F8           = 61
    F9           = 62
    F10          = 63
    F11          = 64
    F12          = 65
    # slot  66 = '<skip>' (skipped / unmapped)
    # slot  67 = '<skip>' (skipped / unmapped)
    # slot  68 = '<skip>' (skipped / unmapped)
    INSERT       = 69
    HOME         = 70
    PAGE_UP      = 71
    DELETE       = 72
    END          = 73
    PAGE_DOWN    = 74
    RIGHT        = 75
    LEFT         = 76
    DOWN         = 77
    UP           = 78
    # slot  79 = '<skip>' (skipped / unmapped)
    # slot  80 = '<skip>' (skipped / unmapped)
    # slot  81 = '<skip>' (skipped / unmapped)
    # slot  82 = '<skip>' (skipped / unmapped)
    # slot  83 = '<skip>' (skipped / unmapped)
    # slot  84 = '<skip>' (skipped / unmapped)
    # slot  85 = '<skip>' (skipped / unmapped)
    # slot  86 = '<skip>' (skipped / unmapped)
    # slot  87 = '<skip>' (skipped / unmapped)
    # slot  88 = '<skip>' (skipped / unmapped)
    # slot  89 = '<skip>' (skipped / unmapped)
    # slot  90 = '<skip>' (skipped / unmapped)
    # slot  91 = '<skip>' (skipped / unmapped)
    # slot  92 = '<skip>' (skipped / unmapped)
    # slot  93 = '<skip>' (skipped / unmapped)
    # slot  94 = '<skip>' (skipped / unmapped)
    # slot  95 = '<skip>' (skipped / unmapped)
    EXTRA        = 96
    MENU         = 97
    # slot  98 = '<skip>' (skipped / unmapped)
    # slot  99 = '<skip>' (skipped / unmapped)
    # slot 100 = '<skip>' (skipped / unmapped)
    # slot 101 = '<esc>' -> duplicate of ESC at slot 37, skipped
    LSHIFT       = 102
    LALT         = 103
    LWIN         = 104
    # slot 105 = '<esc>' -> duplicate of ESC at slot 37, skipped
    RSHIFT       = 106
    RALT         = 107
    # slot 108 = '<skip>' (skipped / unmapped)
    # slot 109 = '<skip>' (skipped / unmapped)
    # slot 110 = '<skip>' (skipped / unmapped)
    # slot 111 = '<skip>' (skipped / unmapped)
    # slot 112 = '<skip>' (skipped / unmapped)
    # slot 113 = '<skip>' (skipped / unmapped)
    # slot 114 = '<skip>' (skipped / unmapped)
    # slot 115 = '<skip>' (skipped / unmapped)
    # slot 116 = '<skip>' (skipped / unmapped)
    # slot 117 = '<skip>' (skipped / unmapped)
    # slot 118 = '<esc>' -> duplicate of ESC at slot 37, skipped
    # slot 119 = '<skip>' (skipped / unmapped)
    # slot 120 = '<media_play_pause>' (skipped / unmapped)
    # slot 121 = '<skip>' (skipped / unmapped)
    # slot 122 = '<skip>' (skipped / unmapped)
    # slot 123 = '<skip>' (skipped / unmapped)
    # slot 124 = '<skip>' (skipped / unmapped)
    # slot 125 = '<skip>' (skipped / unmapped)
    # slot 126 = '<skip>' (skipped / unmapped)
    # slot 127 = '<skip>' (skipped / unmapped)
    # slot 128 = '<skip>' (skipped / unmapped)
    # slot 129 = '<skip>' (skipped / unmapped)
    # slot 130 = '<skip>' (skipped / unmapped)
    # slot 131 = '<skip>' (skipped / unmapped)
    # slot 132 = '<skip>' (skipped / unmapped)
    # slot 133 = '<skip>' (skipped / unmapped)
    # slot 134 = '<skip>' (skipped / unmapped)
    # slot 135 = '<skip>' (skipped / unmapped)


SLOT_COUNT = 136

_KEY_NAMES: dict[str, Key] = {k.name: k for k in Key}


def key_from_name(name: str) -> Key:
    normalized = name.upper().replace(' ', '_')
    if normalized not in _KEY_NAMES:
        raise KeyError(f'Unknown key: {name!r}')
    return _KEY_NAMES[normalized]


def all_keys() -> list[Key]:
    return list(Key)
